# Generated by Django 5.1.7 on 2025-03-09 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('followers', models.IntegerField()),
            ],
            options={
                'db_table': 'Author',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('offer_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'Offer',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.IntegerField(primary_key=True, serialize=False)),
                ('publisher_name', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Publisher',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cover_image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('book_title', models.CharField(max_length=255)),
                ('book_description', models.CharField(blank=True, max_length=255, null=True)),
                ('book_softcopy_link', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
            options={
                'db_table': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('subscription_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subscription_name', models.CharField(max_length=255, unique=True)),
                ('duration', models.IntegerField()),
                ('price', models.IntegerField()),
                ('subscribers', models.IntegerField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.offer')),
            ],
            options={
                'db_table': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('fellow_reviewers', models.IntegerField(null=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subscriptions')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('reviews', models.CharField(max_length=255)),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'Review',
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('feed_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('upvotes', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'Feed',
            },
        ),
        migrations.CreateModel(
            name='AuthorBooks',
            fields=[
                ('author_author', models.OneToOneField(db_column='Author_author_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.author')),
                ('books_book', models.ForeignKey(db_column='Books_book_id', on_delete=django.db.models.deletion.CASCADE, to='app.books')),
            ],
            options={
                'db_table': 'Author_Books',
                'unique_together': {('author_author', 'books_book')},
            },
        ),
        migrations.CreateModel(
            name='BooksPublisher',
            fields=[
                ('books_book', models.OneToOneField(db_column='Books_book_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.books')),
                ('publisher_publisher', models.ForeignKey(db_column='Publisher_publisher_id', on_delete=django.db.models.deletion.CASCADE, to='app.publisher')),
            ],
            options={
                'db_table': 'Books_Publisher',
                'unique_together': {('books_book', 'publisher_publisher')},
            },
        ),
        migrations.CreateModel(
            name='PublisherUser',
            fields=[
                ('publisher_publisher', models.OneToOneField(db_column='Publisher_publisher_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.publisher')),
                ('user_user', models.ForeignKey(db_column='User_user_id', on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'Publisher_User',
                'unique_together': {('publisher_publisher', 'user_user')},
            },
        ),
        migrations.CreateModel(
            name='UserAuthor',
            fields=[
                ('user_user', models.OneToOneField(db_column='User_user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.user')),
                ('author_author', models.ForeignKey(db_column='Author_author_id', on_delete=django.db.models.deletion.CASCADE, to='app.author')),
            ],
            options={
                'db_table': 'User_Author',
                'unique_together': {('user_user', 'author_author')},
            },
        ),
    ]
